covid/urls.py
from . import views
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', views.EmployerListView, name='employers'),
    url(r'^employer/(?P<pk>\d+)$', views.EditEmployer, name='employer-detail'),
    url(r'^employer/delete/(?P<pk>\d+)$', views.DeleteEmployer, name='employer-delete'),
    url(r'^employer/create/$', views.CreateEmployer, name='employer-create'),
    url(r'^parse/$', views.ParseEmployer, name='employer-parse'),
    url(r'^report/$', views.CreateReport, name='employer-report'),
    url(r'^report/download/1/$', views.TuesdayThursday, name='employer-report123'),
    url(r'^report/download/2/$', views.Monday, name='employer-reportmon'),
    url(r'^report/download/3/$', views.EveryDay, name='employer-reporteveryday'),
    url(r'^report/download/4/$', views.Monday16, name='employer-reportmon16'),
    url(r'^employer/filter/(?P<index_group>\d+)$', views.EmployerFilter, name='employer-filter'),
    # url(r'^works/$', views.ResearchListView.as_view(), name='works'),
    # url(r'^work/(?P<pk>\d+)$', views.ResearchDetailView.as_view(), name='work-detail'),
    # url(r'^students/$', views.StudentListView.as_view(), name='students'),
    # url(r'^student/(?P<pk>\d+)$', views.StudentDetailView.as_view(), name='student-detail'),
    # url(r'^teachers/$', views.TeacherListView.as_view(), name='teachers'),
    # url(r'^teacher/(?P<pk>\d+)$', views.TeacherDetailView, name='teacher-detail'),
    # url(r'^works/teacher/(?P<pk>\d+)$', views.TeacherWorksView, name='teacher-works'),
    # url(r'^teachers/create/$', views.CreateTeacher, name='create-teacher'),
    # url(r'^teachers/delete/(?P<pk>\d+)$', views.DeleteTeacher, name='delete-teacher'),
    # url(r'^teachers/edit/(?P<pk>\d+$)', views.EditTeacher, name='edit-teacher'),
    # url(r'^students/create/$', views.CreateStudent, name='create-student'),
    # url(r'^students/delete/(?P<pk>\d+)$', views.DeleteStudent, name='delete-student'),
    # url(r'^students/edit/(?P<pk>\d+$)', views.EditStudent, name='edit-student'),
    # url(r'^works/create/$', views.CreateResearch, name='create-work'),
    # url(r'^works/delete/(?P<pk>\d+)$', views.DeleteResearch, name='delete-work'),
    # url(r'^works/edit/(?P<pk>\d+$)', views.EditResearch, name='edit-research'),
    # url(r'^teachers/search/$', views.SearchTeacherView.as_view(), name='search_teacher_results'),
    # url(r'^students/search/$', views.SearchStudentView.as_view(), name='search_student_results'),
    # url(r'^works/search/$', views.SearchResearchView.as_view(), name='search_work_results'),
]

covid19db/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
     path('covid/', include('covid.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/covid/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Employer(models.Model):
    fullname = models.CharField(max_length=200, null=False, help_text="ФИО сотрудника")
    birthdate = models.CharField(max_length=20, null=True, blank=True, help_text="Дата рождения")
    liveplace = models.TextField(null=False, help_text="Место жительства")
    employers_department = (
        ('1', 'Административно-хозяйственная часть'),
        ('2', 'Аспирантура'),
        ('3', 'Библиотека'),
        ('4', 'деканат факультета мониторинга окружающей среды'),
        ('5', 'деканат факультета повышения квалификации и переподготовки'),
        ('6', 'деканат факультета экологической медицины'),
        ('7', 'Директорат'),
        ('8', 'кафедра дополнительного образования'),
        ('9', 'кафедра иммунологии'),
        ('10', 'кафедра информационных технологий в экологии и медицине'),
        ('11', 'кафедра лингвистических дисциплин и межкультурных коммуникаций'),
        ('12', 'кафедра общей биологии и генетики'),
        ('13', 'кафедра общей и медицинской физики'),
        ('14', 'кафедра социально-гуманитарных наук и устойчивого развития'),
        ('15', 'кафедра физического воспитания'),
        ('16', 'кафедра экологического мониторинга и менеджмента'),
        ('17', 'кафедра экологической медицины и радиобиологии'),
        ('18', 'кафедра экологической химии и биохимии'),
        ('19', 'кафедра энергоэффективных технологий'),
        ('20', 'кафедра ядерной и радиационной безопасности'),
        ('21', 'Научно-исследовательский сектор'),
        ('22', 'Отдел бухгалтерского учета, отчетности и финансирования'),
        ('23', 'Отдел воспитательной работы с молодежью'),
        ('24', 'Отдел закупок и материально-технического снабжения'),
        ('25', 'Отдел кадровой и организационной работы'),
        ('26', 'Отдел международных связей'),
        ('27', 'Отдел технических средств обучения и коммуникаций'),
        ('28', 'Планово-экономический сектор'),
        ('29', 'Спортивный клуб'),
        ('30', 'учебная лаборатория экологической биотехнологии'),
        ('31', 'Учебно-методическая лаборатория инновационных технологий образования'),
        ('32', 'учебно-методическая лаборатория экологического образования'),
        ('33', 'Учебно-методический отдел'),
        ('34', 'Учебный корпус (ул.Ботаническая, 15)'),
        ('35', 'Учебный корпус № 1 (Долгобродская, 23)'),
        ('36', 'Факультет экологической медицины')
    )
    department = models.CharField(max_length=2, null=False, choices=employers_department, default=None, help_text="Подразделение")
    position = models.CharField(max_length=200, null=False, help_text="Должность")
    datefirst = models.DateField(null=True, blank=True, help_text="Дата первой вакцинации")
    datesecond = models.DateField(null=True, blank=True, help_text="Дата второй вакцинации")
    sertification = models.BooleanField(help_text="Наличие сертификата", default=False)
    sertificateid = models.CharField(max_length=40, help_text="", null=True, blank=True)
    vactinationplace1 = models.CharField(max_length=100, null=True, blank=True, help_text="Место первой вакцинации")
    vactinationplace2 = models.CharField(max_length=100, null=True, blank=True, help_text="Место второй вакцинации")
    vactinationfull = models.BooleanField(help_text="Полная вакцинация", default=False)
    wantmake = models.BooleanField(help_text="Желает ли сделать", default=False)
    wantmaketype = models.CharField(max_length=50, help_text="Тип прививки", null=True, blank=True)
    contraindications = models.CharField(max_length=100, help_text="Противопоказания", null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.fullname

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('employer-detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>ISEI</title>{% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.6.4/dat.gui.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/animsition.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">

</head>
<body class="animsition" style="animation-duration: 1.1s; opacity: 1;">
<header class="main-header">
    <div class="container">
        <div class="logo"></div>
        <div class="menu">
            <nav class="desktop-nav">
                {% block sidebar %}
                    <ul class="first-level">
                        <li><a href="{% url 'employers' %}">Главная</a></li>
                        {% if perms.covid.delete_employer %}
                            <li><a href="{% url 'employer-report' %}">Отчеты</a></li>
                            <li><a href="{% url 'employer-parse' %}">Парсинг</a></li>
                            <li><a href="">Подразделения</a>
                                <ul class="second-level">
                                    {% for index, department_name in department_list %}
                                        <li style="width: 400px;"><a href="{% url 'employer-filter' index %}"
                                                                     class="animsition-link"
                                                                     style="font-size: 10px;">{{ department_name|truncatechars_html:40 }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <li><a href="">Пользователь: {{ user.get_username }}</a></li>
                            <li><a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{ request.path }}">Войти</a></li>
                        {% endif %}
                    </ul>
                {% endblock %}
            </nav>
            <nav class="mobile-nav" style="display: none;">
                <ul class="first-level">
                    <li><a href="{% url 'employers' %}">Главная</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="">Пользователь: {{ user.get_username }}</a></li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Войти</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="menu-icon">
                <div class="line" style="width: 30px;"></div>
                <div class="line" style="width: 30px;"></div>
                <div class="line" style="width: 30px;"></div>
            </div>
        </div>
    </div>
</header>
{% block content %}{% endblock %}
{% block pagination %}
    {% if is_paginated %}
        <div class="container">
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <div class="prev-next" style="float: left">
                        <form>
                            <input type="button" value="Назад" class="btn-pagination"
                                   onClick='location.href="{{ request.path }}?page={{ page_obj.previous_page_number }}"'>
                        </form>
                    </div>
                {% endif %}
                <div class="page-current" style="float: left">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </div>
                {% if page_obj.has_next %}
                    <div class="prev-next" style="float: left">
                        <form>
                            <input type="button" value="Далее" class="btn-pagination"
                                   onClick='location.href="{{ request.path }}?page={{ page_obj.next_page_number }}"'>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/smoothScroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.animsition.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base_generic.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <section>
        <div class="container">
            <div class="h1">
                {% if perms.covid.delete_employer %}
                    {% if group_name_filter %}
                        <h1>Список сотрудников подразделения "{{ group_name_filter }}"</h1>
                    {% else %}
                        <h1>Список сотрудников всех подразделений</h1>
                    {% endif %}
                {% else %}
                    <h1>Список сотрудников подразделения "{{ group_name }}"</h1>
                {% endif %}
            </div>
            <div class="col-md-12">
                {% if employer_list %}
                    {% for employer in employer_list %}
                        <div class="col-md-12"
                             style="border: 2px solid #7beec7; border-radius: 13px; margin-bottom: 10px">
                            <div style="margin-bottom: 30px"></div>
                            <div class="list-margin" style="margin-left: 25px;">
                                <div class="section-title"
                                     style="text-align:left;float:left;width:100%;margin-bottom:0">
                                    <span><a href="{{ employer.get_absolute_url }}">{{ employer.fullname }}</a></span>
                                    <p class="plan_price montserrat-text uppercase"><a
                                            href="{% url 'employer-filter' employer.department %}">{{ employer.get_department_display }}</a>
                                    </p>
                                </div>
                                <p>
                                    {% if employer.datefirst %}
                                        <text id="firstvact">Дата первой вакцинации: {{ employer.datefirst }}</text>
                                        <script>
                                            var d = new Date();
                                            var selecteddate = new Date("{{ employer.datefirst.isoformat }}")
                                            var difference = (d - selecteddate)
                                            if (difference > 15811200000) {
                                                document.getElementById('firstvact').style.color = 'red';
                                            }
                                        </script>
                                    {% else %}
                                        Дата первой вакцинации: не вакцинирован
                                    {% endif %}
                                    <br>
                                    {% if employer.datesecond %}
                                        <text id="secondvact">Дата второй вакцинации: {{ employer.datesecond }}</text>
                                        <script>
                                            var d = new Date();
                                            var selecteddate = new Date("{{ employer.datesecond.isoformat }}")
                                            var difference = (d - selecteddate)
                                            if (difference > 15811200000) {
                                                document.getElementById('secondvact').style.color = 'red';
                                            }
                                        </script>
                                    {% else %}
                                        Дата второй вакцинации: не вакцинирован
                                    {% endif %}
                                    <br>
                                    Сотрудник полностью вакцинирован:
                                    {% if employer.vactinationfull == True %}
                                        <input type="checkbox" checked="checked" disabled
                                               style="width: 23px; height: 23px; vertical-align: middle; margin-top: 0;margin-left: 10px;">
                                    {% else %}
                                        <input type="checkbox" disabled
                                               style="width: 23px; height: 23px; vertical-align: middle; margin-top: 0;margin-left: 10px;">
                                    {% endif %}
                                    <br>
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-12">
                        <div class="list-margin">
                            <div class="section-title">
                                <span>Сотрудники не найдены</span>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            {% if perms.covid.delete_employer %}
                <div class="col-md-12">
                    <div class="list-margin">
                        <div class="section-title">
                            <span><a href="{% url 'employer-create' %} " class="btn green" style="bottom: -70px">Добавить сотрудника</a></span>
                        </div>
                    </div>
                </div>

            {% endif %}
        </div>
    </section>
{% endblock %}